<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion><parent><groupId>org.clinx.example</groupId><artifactId>reactor</artifactId><version>1.0-SNAPSHOT</version></parent>
  <artifactId>application</artifactId>
  <dependencies>
    <dependency><groupId>org.clinx.example</groupId><artifactId>policy</artifactId><version>${project.version}</version></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
  </dependencies>
</project>
